---

- src: https://github.com/geerlingguy/ansible-role-repo-epel
  name: repo-epel

- src: https://github.com/geerlingguy/ansible-role-postgresql
  version: "1.3.0"
  name: postgres

- src: https://github.com/geerlingguy/ansible-role-docker
  version: "2.0.4"
  name: docker
