---

- hosts: all
  become: yes
  roles:
    - repo-epel
    - kernel-update
    - docker

- hosts: atc
  become: yes
  roles:
    - postgres
    - concourse-ci

- hosts: worker
  become: yes
  roles:
    - concourse-ci
