---

- name: Get the kernel version
  command: uname -r
  register: kernel_version
  changed_when: false
  check_mode: no

- name: Update the kernel
  include: update.yml
  when: kernel_version.stdout is defined and kernel_version.stdout | version_compare('3.19.0', '<')
