---

- name: Add EPEL kernel repo gpg key
  rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present

- name: Install EPEL kernel yum repo
  yum:
    name: "{{ epel_kernel_repo_url }}"
    state: present

- name: Install latest stable kernel
  yum:
    name: kernel-ml
    enablerepo: elrepo-kernel
    state: present

- name: Set default kernel version in GRUD
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: 'GRUB_DEFAULT=0'

- name: Recreate kernel configuration
  command: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Rebooting ...
  command: bash -lc "/bin/sleep 2 && /sbin/shutdown -r now 'Reboot required for updated kernel'"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for ssh port to open again
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 180
  connection: local
  become: false

- name: Wait a little longer to make sure everything is up
  pause:
    seconds: 5
