---

- name: Create the concourse account
  include: account.yml

- name: Install concourse
  include: install.yml

- name: Create directory for concourse keys
  file:
    path: /etc/concourse
    state: directory
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: 0700

- name: Configure web
  include: web.yml
  when: concourse_web

- name: Configure worker
  include: worker.yml
  when: concourse_worker
