---

- name: Create the concourse account
  include: account.yml

- name: Install concourse
  include: install.yml

- name: Configure web
  include: web.yml
  when: concourse_web

- name: Configure worker
  include: worker.yml
  when: concourse_worker
