---

- name: Restart concourse-web
  service:
    name: concourse-web
    state: restarted
  when: concourse_web

- name: Restart concourse-worker
  service:
    name: concourse-worker
    state: restarted
  when: concourse_worker
